version: "3.8"

services:
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - 6379:6379

  client:
    build: ./chatapp
    restart: always
    ports:
      - 80:80
    depends_on:
      - server

  server:
    build: ./chat_server
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - redis
